name: conda test 2

on:
  workflow_dispatch
  
jobs:
  test:
    name: test conda 2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
      - name: create environent from file
        run: conda env create -f EBIsearch_environment.yml
      - name: initiate
        run: conda init
      - name: activate environment
        run: conda activate EBIsearch
