name: conda test 2

on:
  workflow_dispatch

jobs:
  default-shell:
    name: Default shell
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: EBIsearch
          environment-file: EBIsearch_environment.yml
      - run: conda info
      - run: conda list
      - run: conda config --show
      
